# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 21:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Device_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('radius', models.IntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('alt', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kynect.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Phone Number Entered Incorrectly', regex='^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$')])),
                ('verified', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Owner_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('apt', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=16)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kynect.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=35)),
                ('dob', models.DateField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='kynect.Device')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kynect.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_limit', models.CharField(max_length=10)),
                ('data_interval', models.CharField(max_length=10)),
                ('cost_per_month', models.IntegerField()),
                ('cost_per_year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kynect.Pet'),
        ),
        migrations.AddField(
            model_name='geofence',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kynect.Pet'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kynect.Device_Type'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kynect.Owner'),
        ),
        migrations.AddField(
            model_name='device',
            name='service_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kynect.Service_Plan'),
        ),
    ]
