# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=13)),
                ('location_longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=13)),
                ('location_date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kynect.Device')),
            ],
        ),
    ]
