# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 16:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kynect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='phone_number',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Phone Number Entered Incorrectly', regex='^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$')]),
        ),
    ]
