# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kynect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='device',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='imei',
            new_name='IMEI',
        ),
        migrations.AddField(
            model_name='device',
            name='device_Name',
            field=models.CharField(default='Hawki', max_length=25),
        ),
        migrations.AddField(
            model_name='device',
            name='location_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='device',
            name='location_Latitude',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='device',
            name='location_Longitude',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
