# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 18:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kynect', '0002_auto_20170719_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Phone Number Entered Incorrectly', regex='^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$')]),
        ),
    ]
