# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kynect', '0002_auto_20160613_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='location_Date',
            new_name='last_Location_Date',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='location_Latitude',
            new_name='last_Location_Latitude',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='location_Longitude',
            new_name='last_Location_Longitude',
        ),
    ]
