# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kynect', '0004_auto_20170719_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='is_verified',
            new_name='email_confirmed',
        ),
    ]
