# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kynect', '0004_device_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_Name',
            field=models.CharField(default='Hawki', max_length=50),
        ),
    ]
