# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kynect', '0005_auto_20160614_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='IMEI',
            field=models.CharField(max_length=15),
        ),
    ]
