# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kynect', '0006_auto_20160614_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_Location_Latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=13)),
                ('last_Location_Longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=13)),
                ('last_Location_Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_Location_Date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_Location_Latitude',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_Location_Longitude',
        ),
        migrations.AddField(
            model_name='marker',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kynect.Device'),
        ),
    ]
