# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kynect', '0008_auto_20160615_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marker',
            new_name='Location',
        ),
    ]
