# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 05:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kynect', '0010_auto_20160616_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kynect.Device'),
        ),
    ]
