# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 21:50
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kynect', '0011_auto_20160616_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=35)),
                ('dob', models.DateField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Phone Number Entered Incorrectly', regex='^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$')])),
                ('verified', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('apt', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=16)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kynect.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_limit', models.CharField(max_length=10)),
                ('data_interval', models.CharField(max_length=10)),
                ('cost_per_month', models.IntegerField()),
                ('cost_per_year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='IMEI',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kynect.Profile'),
        ),
        migrations.AddField(
            model_name='pet',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kynect.Device'),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kynect.Profile'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kynect.Device_Type'),
        ),
        migrations.AddField(
            model_name='device',
            name='service_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kynect.Service_Plan'),
        ),
    ]
