# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kynect', '0012_auto_20170714_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('apt', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=16)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='Owner',
        ),
        migrations.RemoveField(
            model_name='profile_address',
            name='user',
        ),
        migrations.AddField(
            model_name='location',
            name='alt',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kynect.Pet'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='kynect.Device'),
        ),
        migrations.DeleteModel(
            name='Profile_Address',
        ),
        migrations.AddField(
            model_name='owner_address',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kynect.Owner'),
        ),
    ]
